### ISSUE TITLE
runs, but display nothing

### ISSUE THREAD

**Issue by HugoCapocci** [artoale/karma-brackets#11] opened 2014-06-17 09:21 UTC
on win7, when I start karma from your extension, my firefox starts according to my karma.conf.js but the "black K" never appears on my brackets... I always have the waiting gif... and the menu still display 'start karma server' , not 'stop karma server' nor 'Launch tests'

further more, I wasn't able to execute "npm install -g karma karma-brackets" because a dependance issue, but "npm install -g karma-brackets"

**Comment by artoale** [comment] 2014-07-04 00:56
Thanks for reporting, the problem is caused by `karma-brackets` currently not supporting karma > 0.12. It will be fixed soon. Thank you for your patience

**Comment by artoale** [comment] 2014-07-04 02:33
Should be closed by v 0.5.1! Please, update the extension (and karma-brackets) and let me know if you have any issue!

**Closed as completed by artoale** 2014-07-04 02:33 UTC
Labels: bug

**Comment by HugoCapocci** [comment] 2014-09-02 10:23
sorry for being long to answer; it works well now, but only with a global (-g) installation of the karma-brackets reporter
